# Generated by Django 5.0.9 on 2026-08-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_token",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[("guest", "Guest"), ("registered", "Registered")],
                        default="guest",
                        max_length=20,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=150, null=True, unique=True
                    ),
                ),
                (
                    "passphrase_hash",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "recovery_code_hash",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("preferred_language", models.CharField(default="en", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
