# Generated by Django 6.0.7 on 2026-07-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('distance_km', models.FloatField(default=0.0)),
                ('faith_sensitive', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
    ]
